### ISSUE TITLE
没有算margin

### ISSUE THREAD

**Issue by robinxdroid** [githubwing/ByeBurgerNavigationView#3]
当FloatingActionButton使用ByeBurgerBottomBehavior时候可以发现问题TranslateAnimateHelper没有算margin

**Comment by githubwing** [comment]
我想了很久。。  很少有底部导航栏带margin的时候吧。。

**Comment by robinxdroid** [comment]
好吧，可能考虑的不同，我想的是，Translate可以用于任何View，比如FloatingActionButton

**Comment by githubwing** [comment]
已修复
