### ISSUE TITLE
CoordinatorLayout布局下的有Orientation这个属性？？

### ISSUE THREAD

**Issue by wangchengmeng** [githubwing/ByeBurgerNavigationView#4]
CoordinatorLayout布局下的有Orientation这个属性么？title和bottom只有在CoordinatorLayout跟布局下才能生效。CoordinatorLayout跟FramLayout一样，那怎么调整两者的位置？

**Comment by githubwing** [comment]
看例子，  有android:layout_gravity="bottom"
